In [1]:
import numpy as np

In [2]:
array1 = np.array([1,3,4,6,3,5,8])

In [6]:
array1

array([1, 3, 4, 6, 3, 5, 8])

In [7]:
print(array1)

[1 3 4 6 3 5 8]


In [11]:
type(array1)
#its a numpy array, not the normal python array
# numpy use for fast calculation of number

numpy.ndarray

In [13]:
array2 = np.array([[1,2,3],[4,5,6]])
# this a two dimention (2D) array

In [14]:
print(array2)

[[1 2 3]
 [4 5 6]]


In [17]:
array2.shape
# this return the shape of the array , like the matrix numbering (row, column)

(2, 3)

In [21]:
array2.dtype
# show which type of data is store in this array

dtype('int32')

In [26]:
array2 = np.array([[1,2,3],[4,5,6.0]])
#data type change to float, all data get float type

In [27]:
array2.dtype

dtype('float64')

In [28]:
print(array2)

[[1. 2. 3.]
 [4. 5. 6.]]


In [33]:
array3 = np.array([1,2,3,4,5.6,6,7,8], dtype='int32')
#force fully make the data type at creation 5.6 value only take 5

In [34]:
array3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
zerosarray = np.zeros((3,6))
# its make a array where all the intial number is 0. , imp- value are in float64
zerosarray


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
onesarray = np.ones((10,8))
onesarray
## this is for one value

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
emptyarray = np.empty((5,6))
# this array create a empty array, does not mean all value should be zero maybe its has some garbage value 
emptyarray

array([[7.43150812e-312, 1.02271589e-321, 0.00000000e+000,
        0.00000000e+000, 8.06635533e-308, 5.02034658e+175],
       [1.58767980e-047, 8.38449354e+165, 6.38735192e-067,
        9.68746118e-071, 1.66759137e-047, 4.26397589e-096],
       [1.12855837e+277, 8.76730979e+252, 2.59027920e-144,
        3.80985069e+180, 1.14428494e+243, 2.59027907e-144],
       [7.79952704e-143, 2.35991414e+184, 4.32196204e-037,
        1.89936126e-052, 3.35036227e-033, 2.59027859e-144],
       [2.59903818e-144, 7.11456189e-091, 3.94467097e-062,
        3.53979009e-057, 1.11475752e+261, 1.16318408e-028]])

In [44]:
add1 = np.array([[1,2,3],[4,5,6]])
add2 = np.array([[8,2,6],[7,1,3]])
sumofarray = add1 + add2
print(sumofarray)

[[ 9  4  9]
 [11  6  9]]


In [45]:
multiofarray = add1 * add2
print(multiofarray)
# its only multiply first to first, second to second,......, n to n 

[[ 8  4 18]
 [28  5 18]]


# slicing
##### numpy slicing new array point to the same number memory address (example below)


In [46]:
main_arr = np.array([1,2,3,4,5,6,7,8,9])

In [47]:
slice_arr = main_arr[4:6]
# its slice array 4 and 5 index and store on this slice_array

In [48]:
slice_arr

array([5, 6])

In [49]:
slice_arr[0] = 50
print(slice_arr)
#chaninging the slice array only but

[50  6]


In [51]:
main_arr
#but this main array gonna change

array([ 1,  2,  3,  4, 50,  6,  7,  8,  9])

In [54]:
#prevent this by
slice_arr = main_arr[4:6].copy()
slice_arr

array([50,  6])

In [56]:
slice_arr[0] = 5
slice_arr

array([5, 6])

In [58]:
main_arr
#now its not changing

array([ 1,  2,  3,  4, 50,  6,  7,  8,  9])